name: fortress_earth
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  malison: ^0.13.0
  piecemeal: ^2.0.0

dev_dependencies:
  args: ^2.4.2
  build_runner: ^2.3.3
  build_web_compilers: ^4.1.5
  image: ^4.2.0
  lints: ^6.0.0
  test: ^1.24.3
