name: fortress_earth
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  malison: ^0.13.0
  piecemeal: ^1.0.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  args: ^2.4.2
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  image: ^4.2.0
  test: ^1.24.3
