name: fortress_earth
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
author: Filip Hracek <filip.hracek@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  howler: ^1.0.2
  malison: ^0.11.3
  piecemeal: ^0.4.2

dev_dependencies:
  args: ^1.5.1
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  image: ^2.0.5
  test: ^1.0.0
